from datetime import datetime, timezone
from typing import List
from ..models.incident import Incident, Severity, Lifecycle, Zone


def fetch_incidents() -> List[Incident]:
    return [
        Incident(
            id="static-001",
            title="Mw 7.8 Earthquake — Gorkha Epicenter",
            description="Major earthquake struck near Gorkha district. Widespread structural damage reported across Sindhupalchok, Gorkha, and Kathmandu valley. Rescue teams mobilized.",
            severity=Severity.CRITICAL,
            lifecycle=Lifecycle.ACTIVE,
            zone=Zone(id="z-gorkha", name="Barpak", district="Gorkha", municipality="Tsum Nubri"),
            latitude=28.147,
            longitude=84.708,
            reported_at=datetime(2015, 4, 25, 6, 11, 26, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 8, 0, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-002",
            title="Mass Landslide — Sindhupalchok",
            description="Multiple landslides triggered by the earthquake have blocked the Araniko Highway. Villages in Tatopani and Kodari are cut off. At least 200 households unreachable.",
            severity=Severity.CRITICAL,
            lifecycle=Lifecycle.ACTIVE,
            zone=Zone(id="z-sindhu-01", name="Tatopani", district="Sindhupalchok", municipality=None),
            latitude=27.971,
            longitude=85.961,
            reported_at=datetime(2015, 4, 25, 7, 30, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 9, 15, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-003",
            title="Building Collapse — Kathmandu Durbar Square",
            description="Kasthamandap and several heritage structures collapsed in Kathmandu Durbar Square. Heavy debris blocking surrounding streets. Casualties reported.",
            severity=Severity.CRITICAL,
            lifecycle=Lifecycle.VERIFIED,
            zone=Zone(id="z-ktm-01", name="Durbar Square", district="Kathmandu", municipality="Kathmandu Metropolitan"),
            latitude=27.704,
            longitude=85.307,
            reported_at=datetime(2015, 4, 25, 6, 20, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 7, 45, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-004",
            title="Mw 6.7 Aftershock — Kodari",
            description="Strong aftershock near Kodari along Nepal-China border. Additional landslides triggered. Border crossing closed indefinitely.",
            severity=Severity.HIGH,
            lifecycle=Lifecycle.VERIFIED,
            zone=Zone(id="z-sindhu-02", name="Kodari", district="Sindhupalchok", municipality=None),
            latitude=27.994,
            longitude=85.957,
            reported_at=datetime(2015, 4, 25, 8, 9, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 8, 30, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-005",
            title="Flash Flood — Melamchi River",
            description="Earthquake-triggered landslide dammed the Melamchi River upstream. Dam-burst flooding now threatening Helambu villages downstream. Evacuation underway.",
            severity=Severity.HIGH,
            lifecycle=Lifecycle.ACTIVE,
            zone=Zone(id="z-sindhu-03", name="Helambu", district="Sindhupalchok", municipality="Helambu Rural"),
            latitude=27.917,
            longitude=85.617,
            reported_at=datetime(2015, 4, 25, 10, 0, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 11, 30, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-006",
            title="Landslide — Rasuwa District",
            description="Large landslide on the Trishuli corridor blocked road access to Rasuwa and Langtang. Trekking groups stranded in Langtang Valley.",
            severity=Severity.HIGH,
            lifecycle=Lifecycle.REPORTED,
            zone=Zone(id="z-rasuwa-01", name="Langtang", district="Rasuwa", municipality=None),
            latitude=28.214,
            longitude=85.515,
            reported_at=datetime(2015, 4, 25, 9, 45, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 9, 45, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-007",
            title="Structural Damage — Bhaktapur Old Town",
            description="Extensive damage to historic brick structures in Bhaktapur Durbar Square. Nyatapola Temple partially damaged. Surrounding residential buildings collapsed.",
            severity=Severity.HIGH,
            lifecycle=Lifecycle.VERIFIED,
            zone=Zone(id="z-bhkt-01", name="Bhaktapur Durbar Square", district="Bhaktapur", municipality="Bhaktapur Municipality"),
            latitude=27.671,
            longitude=85.429,
            reported_at=datetime(2015, 4, 25, 7, 0, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 8, 20, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-008",
            title="Mw 5.1 Aftershock — Dolakha",
            description="Moderate aftershock recorded in Dolakha district. Additional cracking in already-damaged buildings. No new casualties confirmed.",
            severity=Severity.MODERATE,
            lifecycle=Lifecycle.REPORTED,
            zone=Zone(id="z-dolakha-01", name="Charikot", district="Dolakha", municipality="Bhimeshwor Municipality"),
            latitude=27.666,
            longitude=86.051,
            reported_at=datetime(2015, 4, 25, 11, 15, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 11, 15, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-009",
            title="Partial Building Collapse — Lalitpur",
            description="Several older brick buildings collapsed in Patan. Rescue teams from Kathmandu re-routed to assist. Streets partially blocked.",
            severity=Severity.MODERATE,
            lifecycle=Lifecycle.ACTIVE,
            zone=Zone(id="z-lalitpur-01", name="Patan", district="Lalitpur", municipality="Lalitpur Metropolitan"),
            latitude=27.666,
            longitude=85.324,
            reported_at=datetime(2015, 4, 25, 6, 45, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 10, 0, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-010",
            title="Road Obstruction — Prithvi Highway",
            description="Rockfall and debris on Prithvi Highway between Malekhu and Mugling. Heavy vehicle traffic suspended. Alternative routes via Tribhuvan Highway being assessed.",
            severity=Severity.MODERATE,
            lifecycle=Lifecycle.VERIFIED,
            zone=Zone(id="z-dhading-01", name="Malekhu", district="Dhading", municipality=None),
            latitude=27.859,
            longitude=84.932,
            reported_at=datetime(2015, 4, 25, 8, 30, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 9, 0, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-011",
            title="Minor Tremor — Nuwakot",
            description="Minor seismic activity felt in Nuwakot. No structural damage reported. Residents advised to stay outdoors as precaution.",
            severity=Severity.LOW,
            lifecycle=Lifecycle.RESOLVED,
            zone=Zone(id="z-nuwakot-01", name="Bidur", district="Nuwakot", municipality="Bidur Municipality"),
            latitude=27.911,
            longitude=85.170,
            reported_at=datetime(2015, 4, 25, 12, 0, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 13, 30, 0, tzinfo=timezone.utc),
        ),
        Incident(
            id="static-012",
            title="Small Landslide — Kavrepalanchok",
            description="Localised landslide on a secondary road near Dhulikhel. Road cleared within hours. No injuries reported.",
            severity=Severity.LOW,
            lifecycle=Lifecycle.RESOLVED,
            zone=Zone(id="z-kavre-01", name="Dhulikhel", district="Kavrepalanchok", municipality="Dhulikhel Municipality"),
            latitude=27.623,
            longitude=85.547,
            reported_at=datetime(2015, 4, 25, 13, 0, 0, tzinfo=timezone.utc),
            updated_at=datetime(2015, 4, 25, 15, 0, 0, tzinfo=timezone.utc),
        ),
    ]
